version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - API_KEY=dev_api_key
      - VECTOR_DB_DIR=/app/data/vector_db
      - PROCESSED_DATA_DIR=/app/data/processed
      - LLM_PROVIDER=groq
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload